baseURL: 'https://juyujeng.github.io/researchlife/'
languageCode: 'zh-tw'
title: Ju' Research and Life
theme: PaperMod
enableGitInfo: true # automatically get information from github, like last updated date
googleAnalytics: G-8XNMY2VF63
staticDir: static
enableEmoji: true 
Params:
  # home info mode
  homeInfoParams:
    Title: Ju' Research and Life
    Content: >
      分享我的研究相關心得與經驗

      - 如果有興趣想要追求身心的平衡 
      
      - 可以參考 [臺灣身心中軸覺察發展中心](https://bmaa.tw) 
  mainSections: # this is importtant, or only blog folder is taken as main section. In that case, posts in docs folder will not show in homepage and archives
    - blog
    - docs
  mathjax: true # Enable MathJax
  defaultTheme: auto
  ShowPostNavLinks: true
  # open comments board
  comments: true
  env: production # to enable google analytics 
  assets:
      favicon: "https://juyujeng.github.io/researchlife/favicon.ico"
      favicon16x16:  "https://juyujeng.github.io/researchlife/favicon-16x16.png"
      favicon32x32:  "https://juyujeng.github.io/researchlife/favicon-32x32.png"
      apple_touch_icon:  "https://juyujeng.github.io/researchlife/apple-touch-icon.png"
  label:
    text: Ju' Research & Life 
    icon: "https://juyujeng.github.io/researchlife/apple-touch-icon.png"


  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: 'About'
      name: 'About Me'
      url: '/about'
      weight: 1
    - identifier: 'Blog'
      name: 'Blog'
      url: '/blog/'
      weight: 2
    - identifier: 'Document'
      name: 'Document'
      url: '/docs/'
      description: 'where to write down some articles'
      weight: 3
    - identifier: 'Tags'
      name: 'Tags'
      url: '/tags/'
      weight: 4
    - identifier: 'Archives'
      name: 'Archives'
      url: '/archives/'
      weight: 5
    - identifier: 'Search'
      name: 'Search'
      url: '/search/'
      weight: 6


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search