baseURL: 'https://juyujeng.github.io/researchlife/'
languageCode: 'zh-tw'
title: "Ju' Research and Life"
theme: 'PaperMod'

params:
  # home info mode
  homeInfoParams:
    Title: 歡迎來到我的網站
    Content: 分享我的研究相關心得與經驗
    
  
  toc: true
  mathjax: true # Enable MathJax
  defaultTheme: auto
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: 'About'
      name: 'About'
      url: '/about'
      weight: 10
    - identifier: 'Blog'
      name: 'Blog'
      url: '/blog/'
      weight: 20
    - identifier: 'Document'
      name: 'Document'
      url: '/docs/'
      weight: 30
    - identifier: 'Tags'
      name: 'Tags'
      url: '/tags/'
      weight: 40
    - identifier: 'Archives'
      name: 'Archives'
      url: '/archives/'
      weight: 50
