baseURL: 'https://juyujeng.github.io/researchlife/'
languageCode: 'zh-tw'
title: "Ju' Research and Life"
theme: 'PaperMod'

params:
  # home info mode
  homeInfoParams:
    Title: 歡迎來到我的網站
    Content: >
      分享我的研究相關心得與經驗

      - 如果有興趣想要追求身心的平衡 
      
      - 可以參考 [臺灣身心中軸覺察發展中心](https://bmaa.tw) 
    
  mathjax: true # Enable MathJax
  enableEmoji: true 
  defaultTheme: auto
  ShowShareButtons: false
  ShowPostNavLinks: true
  # open comments board
  comments: false 
  googleAnalytics: G-8XNMY2VF63

menu:
  main:
    - identifier: 'About'
      name: 'About Me'
      url: '/about'
      weight: 1
    - identifier: 'Blog'
      name: 'Blog'
      url: '/blog/'
      weight: 2
    - identifier: 'Document'
      name: 'Document'
      url: '/docs/'
      description: 'where to write down some articles'
      weight: 3
    - identifier: 'Tags'
      name: 'Tags'
      url: '/tags/'
      weight: 4
    - identifier: 'Archives'
      name: 'Archives'
      url: '/archives/'
      weight: 5
    - identifier: 'Search'
      name: 'Search'
      url: '/search/'
      weight: 6


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search